---
# code BY Triadz Kaiden
# ================= PHREAKER ==================
rule-providers:
  Playstore:
    type: file
    behavior: domain
    path: "./rule_provider/playstore.yaml"
  Meta:
    type: file
    behavior: domain
    path: "./rule_provider/meta.yaml"
  Sosmed:
    type: file
    behavior: classical
    path: "./rule_provider/sosmed.yaml"
  Telegram:
    type: file
    behavior: classical
    path: "./rule_provider/telegram.yaml"
  Streaming:
    type: file
    behavior: classical
    path: "./rule_provider/streaming.yaml"
  Tiktok:
    type: file
    behavior: classical
    path: "./rule_provider/tiktok.yaml"
  Whatsapp:
    type: file
    behavior: classical
    path: "./rule_provider/whatsapp.yaml"
  Youtube:
    type: file
    behavior: classical
    path: "./rule_provider/youtube.yaml"
  Speedtest:
    type: file
    behavior: classical
    path: "./rule_provider/speedtest.yaml"
  Bank:
    type: file
    behavior: domain
    path: "./rule_provider/banks.yaml"
  Direct:
    type: file
    behavior: classical
    path: "./rule_provider/direct.yaml"
  Reject:
    type: file
    behavior: classical
    path: "./rule_provider/reject.yaml"
proxy-providers:
  AKUN-ID:
    type: file
    path: "./proxy_provider/ID.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 30
  AKUN-SG:
    type: file
    path: "./proxy_provider/SG.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 30
proxy-groups:
- name: 🚥AUTO🚥
  type: fallback
  disable-udp: false
  use:
  - AKUN-ID
  - AKUN-SG
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: UMUM 🌏
  type: select
  disable-udp: false
  proxies:
  - 🚥AUTO🚥
  - ID🇲🇨
  - SG🇸🇬
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: BANK 🏧
  type: select
  disable-udp: false
  proxies:
  - 🚥AUTO🚥
  - ID🇲🇨
  - SG🇸🇬
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: SOSMED 📲
  type: select
  disable-udp: false
  proxies:
  - 🚥AUTO🚥
  - ID🇲🇨
  - SG🇸🇬
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: STREAMING 📽️
  type: select
  disable-udp: false
  proxies:
  - 🚥AUTO🚥
  - ID🇲🇨
  - SG🇸🇬
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: SPEEDTEST 🚀
  type: select
  disable-udp: false
  proxies:
  - ID🇲🇨
  - SG🇸🇬
  - DIRECT
- name: SG🇸🇬
  type: select
  disable-udp: false
  use:
  - AKUN-SG
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: ID🇲🇨
  type: select
  disable-udp: false
  use:
  - AKUN-ID
  url: http://www.gstatic.com/generate_204
  interval: '120'
# ================= DP  ==================
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: 'xidz'
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  nameserver:
  - https://dns.google/dns-query
  fallback:
  - https://cloudflare-dns.com/dns-query
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  proxy-server-nameserver:
  - 104.17.241.25 #IP NETFLIX
  - 104.17.237.25 #IP NETFLIX
  - 170.114.45.6 #IP XCV
  - 170.114.46.6 #IP XCV
  - 104.18.213.235 #IP XCV
  - 104.18.214.235 #IP XCV
  - 112.215.203.246
  - 112.215.203.247
  - 112.215.203.248
  - 112.215.203.254
  - 112.215.198.248
  - 112.215.198.254
  - '[2400:9800:2:2::245]'
  - '[2400:9800:2:2::246]'
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "+.*"
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
tcp-concurrent: true
sniffer:
  enable: true
  parse-pure-ip: true
geodata-loader: memconservative
keep-alive-interval: 1800
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Playstore,UMUM 🌏
- RULE-SET,Meta,SOSMED 📲
- RULE-SET,Sosmed,SOSMED 📲
- RULE-SET,Telegram,SOSMED 📲
- RULE-SET,Whatsapp,SOSMED 📲
- RULE-SET,Streaming,STREAMING 📽️
- RULE-SET,Youtube,STREAMING 📽️
- RULE-SET,Tiktok,STREAMING 📽️
- RULE-SET,Bank,BANK 🏧
- RULE-SET,Speedtest,SPEEDTEST 🚀
- RULE-SET,Reject,REJECT
- RULE-SET,Direct,DIRECT
- MATCH,UMUM 🌏
